version: "3.9"
   
services:
    medisearch:
        build: .
        container_name: medisearch
        command: python manage.py runserver 0.0.0.0:80
        volumes:
            - .:/usr/src/app
        ports:
            - "80:80"
        depends_on:
            - pgdb
    pgdb:
        image: postgres
        container_name: pgdb
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - pgdata:/var/lib/postgresql/data/
volumes:
    pgdata: