# Generated by Django 3.2.7 on 2021-09-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=255, null=True)),
                ('tag_link', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PubmedDatabase',
            fields=[
                ('id_name', models.AutoField(primary_key=True, serialize=False, verbose_name='Article ID')),
                ('author', models.TextField(blank=True, null=True, verbose_name='Author Name')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Article Title')),
                ('abstracts', models.TextField(blank=True, null=True, verbose_name='Abstracts')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='Keywords')),
                ('tags', models.ManyToManyField(blank=True, to='apis.Tag')),
            ],
        ),
    ]
